name: CI

on: [push, pull_request]

jobs:
  start:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run tests
        run: |
          pip install -r tests/requirements.txt
          pytest tests/ -v